# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtO5UvsD_6-EJkDEPtViGw19eOl3QVvr
"""

import requests
from typing import List, Dict, Any
import json

# --- Configuration ---
# Replace with the public URL from ngrok when the API server is running
API_URL = "https://ec1e-34-125-234-98.ngrok-free.app/"  # Example format

# --- Test Cases ---
test_cases = [
    {
        "query": "I signed a contract with a vendor for custom parts, and they are two weeks late on delivery. What should I do?",
        "mock_answers": [
            "The contract specified delivery within 4 weeks.",
            "I have emails discussing the delays and potential impacts.",
            "The delay is causing me to miss a project deadline, resulting in lost revenue.",
            "The vendor hasn't offered a revised delivery date."
        ]
    },
    {
        "query": "My customer is refusing to pay for goods delivered because they claim the quality is poor, even though they signed off on samples.",
        "mock_answers": [
            "The contract included a clause on quality standards based on approved samples.",
            "I have documented the customer's approval of the samples.",
            "The customer is now claiming the entire batch is unusable.",
            "We have offered to inspect the goods together, but they refused."
        ]
    },
    # Add more test cases if needed
]

# --- Evaluation Functions ---
def evaluate_part1(query: str, response: Dict[str, Any]) -> Dict[str, Any]:
    print(f"\n--- Evaluating Part 1 for Query: {query} ---")
    print("Generated Questions:")
    for i, q in enumerate(response.get('questions', [])):
        print(f"{i+1}. {q}")
    print(f"\nCase Summary: {response.get('case_summary', 'N/A')}")

    evaluation = {
        'Has 4 Questions': len(response.get('questions', [])) == 4
    }
    return evaluation

def evaluate_part2(query: str, response: Dict[str, Any]) -> Dict[str, Any]:
    print(f"\n--- Evaluating Part 2 for Query: {query} ---")
    print("a) Relevant Legal Sections and Articles:")
    print(response.get('relevant_legal_sections', 'N/A'))
    print("\nb) Suggested Legal Procedures:")
    print(response.get('suggested_legal_procedures', 'N/A'))
    print("\nc) Strategic Advice:")
    print(response.get('strategic_advice', 'N/A'))
    print("\nd) Estimated Outcome:")
    print(response.get('estimated_outcome', 'N/A'))

    evaluation = {
        'Has All Sections': all(response.get(section) for section in [
            'relevant_legal_sections', 'suggested_legal_procedures',
            'strategic_advice', 'estimated_outcome'
        ])
    }
    return evaluation

# --- Run Evaluation ---
if __name__ == "__main__":
    if "your-ngrok-url" in API_URL:
        print("\n⚠️ Please replace 'your-ngrok-url' with your actual ngrok public URL.")
    else:
        all_part1_evaluations = []
        all_part2_evaluations = []

        for case in test_cases:
            query = case["query"]
            mock_answers = case["mock_answers"]

            print(f"\n--- Processing Test Case: {query} ---")

            try:
                print("Calling /generate_part1...")
                part1_res = requests.post(f"{API_URL}/generate_part1", json={"query": query})
                part1_res.raise_for_status()
                part1_response = part1_res.json()
                part1_eval = evaluate_part1(query, part1_response)
                all_part1_evaluations.append(part1_eval)

                print("Calling /generate_part2...")
                part2_res = requests.post(f"{API_URL}/generate_part2", json={
                    "query": query,
                    "case_summary": part1_response.get('case_summary', ''),
                    "answers": mock_answers
                })
                part2_res.raise_for_status()
                part2_response = part2_res.json()
                part2_eval = evaluate_part2(query, part2_response)
                all_part2_evaluations.append(part2_eval)

            except requests.exceptions.RequestException as e:
                print(f"❌ Request error for query '{query}': {e}")
            except Exception as e:
                print(f"❌ Unexpected error for query '{query}': {e}")

        # --- Accuracy Report ---
        print("\n--- Evaluation Report ---")

        if all_part1_evaluations:
            count = len(all_part1_evaluations)
            correct = sum(e['Has 4 Questions'] for e in all_part1_evaluations)
            accuracy = (correct / count) * 100
            print(f"✅ Part 1 - Clarifying Questions Accuracy: {accuracy:.2f}% ({correct}/{count})")

        if all_part2_evaluations:
            count = len(all_part2_evaluations)
            correct = sum(e['Has All Sections'] for e in all_part2_evaluations)
            accuracy = (correct / count) * 100
            print(f"✅ Part 2 - Legal Analysis Section Accuracy: {accuracy:.2f}% ({correct}/{count})")